import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import SpaceBackground from "@/components/background";
import BlackHoleButton from "@/components/BlackHoleButton";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body> */}
      <body className="m-0 p-0 overflow-x-hidden">
        {/* 1) Nebula image */}
        <div className="fixed inset-0 -z-20">
          <Image
            src="/7.png"
            alt="Nebula background-"
            fill
            style={{ objectFit: "cover" }}
            priority
          />
        </div>

        {/* 2) Three.js canvas */}
        <SpaceBackground />
        <BlackHoleButton />

        {/* 3) Your scrolling content */}
        <main className="relative z-10">{children}</main>
      </body>
    </html>
  );
}
